### ISSUE TITLE
CI/CD Pipeline

### ISSUE THREAD

**Issue by mcloudmerlin** [SENG-371/SENG371-Frontend#1]

**Comment by jacksonmac** [comment]
![Continuous Integration_Continuous Deployment Pipeline_](https://user-images.githubusercontent.com/118778100/222938869-8b1dec6b-7482-4d35-89c6-3f5d4c298df2.png)
let me know if you guys want any changes, if not all add it to the wiki

**Comment by jacksonmac** [comment]
Text just needs to be copied to the wiki from the google doc then this is ready to be closed

**Comment by mcloudmerlin** [comment]
Text added
